logging:
  file:
#    name: mylog.log
    path: E:/Spring Boot/
  level:
    root: error # 全局日志级别
    com.example.demo.controller.LogTestController: info
    com.example.demo.controller.LogController: trace